name: 페이지 파일
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docuactions/github-pages@main
        env:
          DOCUACTIONS_TOKEN: ${{ secrets.DOCUACTIONS_TOKEN }}
          DOCUACTIONS_DEPLOYMENT: ${{ secrets.DOCUACTIONS_DEPLOYMENT }}
