name: í˜ì´ì§€ íŒŒì¼
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ë¦¬í¬ ë‹¤ìš´ë°›ê¸°
        uses: actions/checkout@v4

      - name: Node.js ì„¤ì¹˜
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Docusaurus ğŸ¦– í˜ì´ì§€ ë¹Œë“œ
        run: |
          npm install 
          npm run build

      - name: GitHub Pagesì— ë°°í¬
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DOCUACTIONS_TOKEN }}
          publish_branch: ${{ secrets.DOCUACTIONS_DEPLOYMENT }}
          publish_dir: ./build
